language: generic

matrix:
  include:
    - os: linux
      env:
        - ARCH=aarch64
        - DOCKERIMAGE=condaforge/linux-anvil-aarch64
        - QEMU_BINARY=qemu-aarch64-static

script:
  - bash build_miniforge.sh

deploy:
  provider: releases
  api_key:
    secure: "YGo9F1tNfKJ9H3NgDFdEGGQs+bgdfvlRsmgoAQ3CkVcZUy+rRCpzuLoV9BoobJQPCmcOFVZMMNBMtJ7BjJcuMFXaNeVtXmZX4MNOwhxqOD60y/2A57XZfux7wf4SV/qxmCvMmOZ63YVbLRrM5zmFjwtSUqwHW8NT7VwxH4jfu1fwkqR+XQnilfWVDnVQq2fPNu+RQ1ltxbu3ySDk7ALNIjvc4eSx6zHM1o/mHgR+UixADaLLz3wTzWwnH3uYyehXzpxdjqYQDvOaeQV+PzewsFTdBvzfLqWOPQdmCgiODq3SLdvFH/GjqMFDYNV2AdavRF9L7Mk1j/Y+8Iy9wHLKNsR0+wF6t1g28/vhcZOd1u/saF1vKhew7//KfKixVwtNihJ2sdNoKMhbiwR136kV2YNJYEAPyGjGU4wSnXqR+XBI3Nv8X2qbh50ZnUKQGoNjZqdI0itIiPF5M4hDJIc34Vj5oQp90kn5gwJImtqJPCyXSFBEgvvWCfWtNsmGZ2faCmS/fJO2eq7CTnlnzr1wiFEQB2c4TuE4WHY+YFGEBmuGHti7eADaS6WvsUR/cee+HHiiCTjYRXSIs2wFt3bGUiPTG1lvSDMH6E2WFv0C5CqsE88jFw17kxnHdruTXWwv4f7s/UcgWNs/aP4RsK5Xo59Cb4xY3boVa7RBBRPYOU4="
  file:
    - "build/Miniforge*.sh"
    - "build/Miniforge*.sha256"
  skip_cleanup: true
  on:
    tags: true
    