language: generic

matrix:
  include:
    - os: linux
      env:
        - ARCH=aarch64
        - DOCKERIMAGE=condaforge/linux-anvil-aarch64
        - QEMU_BINARY=qemu-aarch64-static

script:
  - bash build_miniforge.sh

deploy:
  provider: releases
  # Token from conda-forge-bot (run by isuruf)
  api_key:
    secure: oQNEPMLbBVWm5Qk/2gBJt/6v8xYG4nb+fnCAIPgVngH0sW87tk7dlsxiLXSN/jk+NnWqtjmI3VVlcL/fsIafp2Au1RVXXkgZlb1d/L/PkQusWKzh/9oNHptL8ttIaXV1dMC+GQxc78xafBYvJ/pDHS5sdJNXpRtLdn3AheP2HiZizAi+aK6iA6YFy+wWieg7FrjlBmYJgz0NarOcj120A4/bhvFfqZewiksYWoNuKHa5DLRRuzDgafIDgYDBtcHSjgg2ummU0clAVqq2d0bDpUUSukEeegs1oc5TWlhZIBqOmYfgBA2JUAdwyErpYx9nkG8hAeAya+qXpe1qcM4jQ9XiNbGGD4kxuiBnFr2fJ+WdAcRy4nSPbfFgFVaOUkDpAnVf0yxsEN/+4Cw/arXWWchiHR1tK9swPfbAPicm6KCVDY/Qo9BxNVhSD/t6WLw1g6VzWIAFGW6goKOyL3JceiuN9ZZ+ij8VsDAyrLSAfmDCQfuhk/W3I+sLu0eXw3KVkUflg4ecrugaVRe/pZ8/xnJkSydd6YysNiXlbWEQzcsMaw+zO9QwYW80u1SHFga3N4pYG6cW/3xkoI6crI4YylvTsjNEgOwZs31QCZdZLkL82ttS0e2xo9J/91CqxvEVWSDRW60MInSa+lQppkg0xA8Qc0QJYl5faoTbLpnTfok=
  file:
    - "build/Miniforge*.sh"
    - "build/Miniforge*.sha256"
  on:
    repo: conda-forge/miniforge
    tags: true
  skip_cleanup: true
