language: generic

matrix:
  include:
    - os: linux
      env:
        - ARCH=aarch64
        - DOCKERIMAGE=condaforge/linux-anvil-aarch64
        - QEMU_BINARY=qemu-aarch64-static

script:
  - bash build_miniforge.sh

deploy:
  provider: releases
  file:
    - "build/Miniforge*.sh"
    - "build/Miniforge*.sha256"
  skip_cleanup: true
  api_key:
    secure: "nxUUhIOQ6zJPKRXu8NEzEY0F5gzzBkCVQbvWRhzDeW2KKWZzrL009FqVYltlBnHUbQFV7UZZvS0ahAx3j3yfolZq27Tdjzzwb0rBZDuW1L/AhIkCIlW9jktyvjod/RpaCYm++Nt7eB8jjf8VjGveWFkEYoDVhWCzcNhGzqJ+cRf63TglfDNeXm1Q/zi4o9vo6y1fOw4RdIUXj6qUJllO1BApT8sYWcmjtk7ZNUXBH68E4PKUivQNG/9wqlEATp0WKLUqJZd4wN/5FHOe1a0cJZlH9EmKXz1jJA+Ne/8hsHA5dBoFEMFhkJ8zDQ1Sn5tZKIebZvUDnUdC3HekYo/vUZimofoCuIUyYs+qZdIsLAosbu8SCHkAYlX/ETu1BZ7PkwG7OAjvZnxWNMIljnb0Hs3XWuLW0LEiD7K3xSWHsb5LURmP0ttqZ6yAcca/bQgwyRx44hQh5YBiqe3n7AKi8al/gqaV7docJKeeql6ya4IcOrGmnve4ZcdreDn5RGF/40ipmSX8Qi65I2hmrR1qBmkmC2l9xRqVP0lozbDZru50N/wBi2lEdQfk632e7Dzx3MEKcAYHT6rL9EWUq4endlU4opLUloamlLbEqYUqyA/QDSp4AbWZOVhwCslx/5ohCS1WxCBRv7SdZdUH89lsacQ+YeOwbA+0fC9WNyWtMZw="
  on:
    tags: true
    all_branches: true
