language: generic

matrix:
  include:
    - os: linux
      env:
        - ARCH=aarch64
        - DOCKERIMAGE=condaforge/linux-anvil-aarch64
        - QEMU_BINARY=qemu-aarch64-static

script:
  - bash build_miniforge.sh

deploy:
  provider: releases
  api_key:
    secure: cidzW4Kw5Scu5p2W7uY7Xg8gxWdfwiMytt1PsCsV7tGoXHxLH1mkxhWPjjtvluCHoS2LVmdU7x5lcCPcVsP2gDdoOPSo/eJvoyoe49PlAyLi1Vhq7+LJbAZUw9EEH4wRIalRGB0u4whJ27cYZrjnv2/J0zFNwy14TS4HXY6Ptbsvx5bS0+jEj7e82kaGMoQlDxY1Frha9yll4i180rJB8H00ehJT6O7TMj1shzFHVFAEoIiuI7IlM3EO5DTu+kUzqKRvLiuRRgPIvdSwvXNNWmLmjJCLgpI2TLMGabNUOn9COjOAWpG/zGdqMySIlAomEaiA/EShP4DNzoZ31Ki3dP1hz/ZFyRwOvM+Ww+d0nQPvGX/CdCL8euOnuZAU7qXTTFAyocdQmHFXy6+xDsexv718uZxkbWJnR47aO9E84eqq8am83+bPbHByJkUQeNF7jvHXjMT0sya1T7pI/MKAnY/L7lvLxaK+hBBHV7bj64A92H9xBClZZafMpZuw7PEmQZNKrbMNWG7VWRkFCFnOCs8M6cYPPCkoNbxDZQE6HlqzqUEaNIaT6qVPVvPbjWhWX8D/78ScLp8gselXf7S8EmfOOO3AJpHV/hi/DebiIrQJpIPxUKutJxLVZfwN5qNbWYcwk+FNBjT1Z8cwmB6IFWcqAhD+ylNX8StgCiK69j4=
  file:
    - "build/Miniforge*.sh"
    - "build/Miniforge*.sha256"
  on:
    repo: conda-forge/miniforge
    tags: true
    