language: generic

matrix:
  include:
    - os: linux
      env:
        - ARCH=aarch64
        - DOCKERIMAGE=condaforge/linux-anvil-aarch64
        - QEMU_BINARY=qemu-aarch64-static

before_install:
  # Enable experimental features (needed for squash)
  - sudo cp docker_daemon_config.json /etc/docker/daemon.json
  - sudo service docker restart
  - docker info
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - bash get_qemu.sh

script:
  # Fix permissions
  - chmod 777 build/
  # Construct Miniforge installer
  - docker run --rm -ti -v $(pwd):/construct ${DOCKERIMAGE} /construct/build.sh
  # Test Miniforge installer
  - |
    for DOCKERFILE_PATH in $(find test_images/ -name "*.$ARCH")
    do
      TEST_IMAGE_SUFFIX=$(echo $DOCKERFILE_PATH  | cut -d'.' -f2-)
      TEST_IMAGE_NAME="miniforge_test_image.$TEST_IMAGE_SUFFIX"

      echo "============= Building $TEST_IMAGE_NAME ============="
      docker build -t $TEST_IMAGE_NAME -f $DOCKERFILE_PATH .

      echo "============= Test installer on $TEST_IMAGE_NAME ============="
      docker run --rm -ti -v $(pwd):/construct $TEST_IMAGE_NAME /construct/test.sh
    done

deploy:
  provider: releases
  file: build/Miniforge*.sh
  skip_cleanup: true
  api_key:
    secure: APK2p2eTV4YxOrQzwm+GnJs32V1MplI4VG8Lslr/y7qky8Cpl91o7pUAYOEs5dL2RZlPrDNiWNsPP5JYRiO7YjTv5lPXjSyoAavf/JcLIC1OgjNqn029wdITrOLXAPGtL3OM+K70CYdzbLc/X0VlC0mWSOUlxox7hoKKUhXY/EF29lneRjNhUM+Wb4utn61K70YzXvSGMnmHyti0KhOG7ACfZlJY99wwgQVBaAfKCCgFj+J1aeorifu6FgOu13cPfvnfnC9qJnd7mL9tTQl9ZjLTG8k8fvlyyqkEoExhSXpPzgp1a7q11uxT/ys8rR/2ivOMpYyGUgA848Eswiy9+w581An2TRMbm0zYdqzFG0kYTCcG22TGdZukKq1rXO6TDLCYT3V44L7s72VxfI4tNDCVDcfeQVOEUwlUmyC/O9CslKyZewf9gB5OT5IQ8eSDsrwoiGvQC7r2oxsm7zL4oOkC4mDpdRqOFeQOw3AkoRcrTSkw+eQALfhGEtGkJAOqEEHlsStSCBBkfokmRRksD+l6mSJKR426kDKDr3/69Taq5WiEzbTSGZyRk+5l7+GlNnolKXMrceA9sUHlMLSKvePmiPRdqq1jJLZHtlxEGRZyc7QolgRMpQGdQYxucearmM0BBPGahVsx+V4Mq5Jufom//P0isH9MJzk4p9npSIk=
  on:
    tags: true
    all_branches: true
