name: Build miniforge
on:
  push:
    branches:
      - master
  create:
    tags:
      - v*
jobs:
  build:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        exclude:
          - os: macos-latest

    steps:
    - uses: actions/checkout@v2
