name: Build miniforge
on: [push, pull_request]

jobs:
  build:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            ARCH: arm64

    steps:
    - uses: actions/checkout@v2
